version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=djangotraining
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: